import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Background from "./ui/background/Background";

const inter = Roboto({ subsets: ['latin'], weight: '300', style: 'normal' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Background />
        <div className="bg-transparent p-6 min-h-screen flex flex-col justify-end items-end">
          <header className="fixed top-0 left-0 p-6">
            <h1 className="text-3xl lg:text-5xl font-bold">Nicola D&apos;Oronzo</h1>
            <h2 className="text-lg font-semibold mb-6">Front-end developer</h2>

            <nav>
              <ul>
                <li>About</li>
                <li>Projects</li>
                <li>Experiences</li>
                <li>On My Bookshelf</li>
                <li>Artworks</li>
              </ul>
            </nav>
          </header>

          <main className="w-2/5 lg:w-1/5 pt-[50vh]">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
